title: "Second Brain"
description: "A bunch of Aniq's notes and write-ups about tech and anything I find interesting"
theme: minima

sass:
  sass_dir: assets/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "./about.html"
  - title: "Portfolio ↗️"
    url: "https://www.aniqaqil.xyz/"
  - title: "Github ↗️"
    url: "https://github.com/aniqaqill/second-brain"
