title: "Second Brain"
description: "A bunch of Aniq's notes and write-ups about tech and anything I find interesting"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "Docker Overview"
    url: "/docker/overview.md"
  - title: "About"
    url: "/about.md"