# Setup
title:               second brain
tagline:             'A Jekyll theme'
description:         'A sub-part of  <a href="https://www.aniqaqil.xyz/" target="_blank">Aniq's Websites</a> that places most of the notes and write-ups. Made by <a href="https://x.com/fmt_aniq" target="_blank">@fmt_aniq</a>.'
url:                 https://www.aniqaqil.xyz/
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Aniq Aqil
  url:               https://x.com/fmt_aniq
  email:             aniqaqil06@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
